### ISSUE TITLE
ark when extracting zip files doesn't overwrite the old version of a file if the new version exists

### ISSUE THREAD

**Issue by thedebugger** [burtlo/ark#93]
We shouldn't use unzip with `-u` option; instead we simpliy just override files.

**Comment by webcoyote** [comment]
I'm encountering this issue when using the [consul cookbook](https://github.com/johnbellone/consul-cookbook). Our servers have consul 0.4.0 installed and should be auto-upgrading to 0.4.1. However, because the ark ````dump```` provider unzips using ````-u```` ("extract files that are newer") the ark recipe won't overwrite the old version of the file.

I'd ask that you please accept PR #94 to fix this issue.

**Comment by xbeta** [comment]
+1 
I have this exact problem, can we get a fix for this?

**Comment by xbeta** [comment]
@burtlo mind to check out this PR and have it merge?

**Comment by burtlo** [comment]
I'll merge this. I've never liked the letter "u".

**Comment by burtlo** [comment]
Issue #94 is merged.
